<fieldset class="admin__fieldset">
    <div class="admin__field ">
        <div class="admin__field-label">
            <lable>Start Time</lable>
        </div>
        <div class="admin__field-control">
            <input disabled class="admin__control-text" type="text" value="<?php echo $block->getcheckValue()['start_time'] ?>">
        </div>
    </div>
    <div class="admin__field">
        <div class="admin__field-label">
            <lable>Start Time</lable>
        </div>
        <div class="admin__field-control">
            <textarea class="admin__control-textarea" type="text"><?php echo $block->getcheckValue()['input'] ?></textarea>
        </div>
    </div>
    <div class="admin__field">
        <div class="admin__field-label">
            <lable for="output">Start Time</lable>
        </div>
        <div class="admin__field-control">
            <textarea id="output" class="admin__control-textarea" type="text"><?php echo $block->getcheckValue()['output'] ?></textarea>
        </div>
    </div>
    <div class="admin__field ">
        <div class="admin__field-label">
            <lable>Start Time</lable>
        </div>
        <div class="admin__field-control">
            <input disabled class="admin__control-text" type="text" value="<?php echo $block->getcheckValue()['end_time'] ?>">
        </div>
    </div>
</fieldset>
